version: '3.8'

services:
  # Servidor web PHP
  app:
    build: .
    container_name: caja_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=caja_user
      - DB_PASSWORD=caja_password
      - DB_NAME=ControlCajaAhorro

  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: caja_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ControlCajaAhorro
      MYSQL_USER: caja_user
      MYSQL_PASSWORD: caja_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./BD.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
